language: python
env:
  - TOXENV=py27-dj15
  - TOXENV=py27-dj16
  - TOXENV=py27-dj17
  - TOXENV=py27-dj18
  - TOXENV=py33-dj15
  - TOXENV=py33-dj16
  - TOXENV=py33-dj17
  - TOXENV=py33-dj18
  - TOXENV=py34-dj17
  - TOXENV=py34-dj18
install:
  - pip install tox
script:
  - export PYTHONPATH=$PYTHONPATH:`pwd`
  - tox
